CREATE TABLE public.p5_regionsolution (
	run_datetime timestamp(0) with time zone NOT NULL,
	intervention numeric(2,0) NOT NULL,
	interval_datetime timestamp(0) with time zone NOT NULL,
	regionid character varying(10) NOT NULL,
	rrp numeric(15,5) NOT NULL,
	rop numeric(15,5) NOT NULL,
	excessgeneration numeric(15,5),
	raise6secrrp numeric(15,5),
	raise6secrop numeric(15,5),
	raise60secrrp numeric(15,5),
	raise60secrop numeric(15,5),
	raise5minrrp numeric(15,5),
	raise5minrop numeric(15,5),
	raiseregrrp numeric(15,5),
	raiseregrop numeric(15,5),
	lower6secrrp numeric(15,5),
	lower6secrop numeric(15,5),
	lower60secrrp numeric(15,5),
	lower60secrop numeric(15,5),
	lower5minrrp numeric(15,5),
	lower5minrop numeric(15,5),
	lowerregrrp numeric(15,5),
	lowerregrop numeric(15,5),
	totaldemand numeric(15,5),
	availablegeneration numeric(15,5),
	availableload numeric(15,5),
	demandforecast numeric(15,5),
	dispatchablegeneration numeric(15,5),
	dispatchableload numeric(15,5),
	netinterchange numeric(15,5),
	lower5mindispatch numeric(15,5),
	lower5minimport numeric(15,5),
	lower5minlocaldispatch numeric(15,5),
	lower5minlocalreq numeric(15,5),
	lower5minreq numeric(15,5),
	lower60secdispatch numeric(15,5),
	lower60secimport numeric(15,5),
	lower60seclocaldispatch numeric(15,5),
	lower60seclocalreq numeric(15,5),
	lower60secreq numeric(15,5),
	lower6secdispatch numeric(15,5),
	lower6secimport numeric(15,5),
	lower6seclocaldispatch numeric(15,5),
	lower6seclocalreq numeric(15,5),
	lower6secreq numeric(15,5),
	raise5mindispatch numeric(15,5),
	raise5minimport numeric(15,5),
	raise5minlocaldispatch numeric(15,5),
	raise5minlocalreq numeric(15,5),
	raise5minreq numeric(15,5),
	raise60secdispatch numeric(15,5),
	raise60secimport numeric(15,5),
	raise60seclocaldispatch numeric(15,5),
	raise60seclocalreq numeric(15,5),
	raise60secreq numeric(15,5),
	raise6secdispatch numeric(15,5),
	raise6secimport numeric(15,5),
	raise6seclocaldispatch numeric(15,5),
	raise6seclocalreq numeric(15,5),
	raise6secreq numeric(15,5),
	aggregatedispatcherror numeric(15,5),
	initialsupply numeric(15,5),
	clearedsupply numeric(15,5),
	lowerregimport numeric(15,5),
	lowerregdispatch numeric(15,5),
	lowerreglocaldispatch numeric(15,5),
	lowerreglocalreq numeric(15,5),
	lowerregreq numeric(15,5),
	raiseregimport numeric(15,5),
	raiseregdispatch numeric(15,5),
	raisereglocaldispatch numeric(15,5),
	raisereglocalreq numeric(15,5),
	raiseregreq numeric(15,5),
	raise5minlocalviolation numeric(15,5),
	raisereglocalviolation numeric(15,5),
	raise60seclocalviolation numeric(15,5),
	raise6seclocalviolation numeric(15,5),
	lower5minlocalviolation numeric(15,5),
	lowerreglocalviolation numeric(15,5),
	lower60seclocalviolation numeric(15,5),
	lower6seclocalviolation numeric(15,5),
	raise5minviolation numeric(15,5),
	raiseregviolation numeric(15,5),
	raise60secviolation numeric(15,5),
	raise6secviolation numeric(15,5),
	lower5minviolation numeric(15,5),
	lowerregviolation numeric(15,5),
	lower60secviolation numeric(15,5),
	lower6secviolation numeric(15,5),
	lastchanged timestamp(0) with time zone,
	totalintermittentgeneration numeric(15,5),
	demand_and_nonschedgen numeric(15,5),
	uigf numeric(15,5),
	semischedule_clearedmw numeric(15,5),
	semischedule_compliancemw numeric(15,5),
	ss_solar_uigf numeric(15,5),
	ss_wind_uigf numeric(15,5),
	ss_solar_clearedmw numeric(15,5),
	ss_wind_clearedmw numeric(15,5),
	ss_solar_compliancemw numeric(15,5),
	ss_wind_compliancemw numeric(15,5),
	wdr_initialmw numeric(15,5),
	wdr_available numeric(15,5),
	wdr_dispatched numeric(15,5),
	ss_solar_availability numeric(15,5),
	ss_wind_availability numeric(15,5),
	raise1secrrp numeric(15,5),
	raise1secrop numeric(15,5),
	lower1secrrp numeric(15,5),
	lower1secrop numeric(15,5),
	raise1seclocaldispatch numeric(15,5),
	lower1seclocaldispatch numeric(15,5),
	bdu_energy_storage numeric(15,5),
	bdu_min_avail numeric(15,5),
	bdu_max_avail numeric(15,5),
	bdu_clearedmw_gen numeric(15,5),
	bdu_clearedmw_load numeric(15,5),
	bdu_initial_energy_storage numeric(15,5)
);

-- Index: public.p5_regionsolution_interval_datetime_idx
CREATE INDEX IF NOT EXISTS p5_regionsolution_interval_datetime_idx
	ON public.p5_regionsolution USING btree
	(interval_datetime ASC NULLS LAST)
	WITH (deduplicate_items='true')
	TABLESPACE pg_default;

-- Index: public.p5_regionsolution_regionid_idx
CREATE INDEX IF NOT EXISTS p5_regionsolution_regionid_idx
	ON public.p5_regionsolution USING btree
	(regionid COLLATE pg_catalog."default" ASC NULLS LAST)
	WITH (deduplicate_items='true')
	TABLESPACE pg_default;

-- Index: public.p5_regionsolution_run_datetime_interval_datetime_regionid_idx
CREATE UNIQUE INDEX IF NOT EXISTS p5_regionsolution_run_datetime_interval_datetime_regionid_idx
	ON public.p5_regionsolution USING btree
	(run_datetime ASC NULLS LAST, interval_datetime ASC NULLS LAST, regionid COLLATE pg_catalog."default" ASC NULLS LAST)
	WITH (deduplicate_items='false')
	TABLESPACE pg_default;
