CREATE OR REPLACE VIEW public.dispatch_regionsum_p5 AS
SELECT dispatch_regionsum.settlementdate,
    'dispatch_regionsum'::text AS source,
    dispatch_regionsum.regionid,
    dispatch_regionsum.totaldemand,
    dispatch_regionsum.availablegeneration,
    dispatch_regionsum.availableload,
    dispatch_regionsum.demandforecast,
    dispatch_regionsum.dispatchablegeneration,
    dispatch_regionsum.dispatchableload,
    dispatch_regionsum.netinterchange,
    dispatch_regionsum.excessgeneration,
    dispatch_regionsum.aggregatedispatcherror,
    dispatch_regionsum.lastchanged,
    dispatch_regionsum.initialsupply,
    dispatch_regionsum.clearedsupply,
    dispatch_regionsum.totalintermittentgeneration,
    dispatch_regionsum.demand_and_nonschedgen,
    dispatch_regionsum.uigf,
    dispatch_regionsum.semischedule_clearedmw,
    dispatch_regionsum.semischedule_compliancemw,
    dispatch_regionsum.ss_solar_uigf,
    dispatch_regionsum.ss_wind_uigf,
    dispatch_regionsum.ss_solar_clearedmw,
    dispatch_regionsum.ss_wind_clearedmw,
    dispatch_regionsum.ss_solar_compliancemw,
    dispatch_regionsum.ss_wind_compliancemw,
    dispatch_regionsum.wdr_initialmw,
    dispatch_regionsum.wdr_available,
    dispatch_regionsum.wdr_dispatched,
    dispatch_regionsum.ss_solar_availability,
    dispatch_regionsum.ss_wind_availability,
    dispatch_regionsum.bdu_energy_storage,
    dispatch_regionsum.bdu_min_avail,
    dispatch_regionsum.bdu_max_avail,
    dispatch_regionsum.bdu_clearedmw_gen,
    dispatch_regionsum.bdu_clearedmw_load,
    dispatch_regionsum.bdu_initial_energy_storage
FROM dispatch_regionsum
UNION ALL
SELECT p5_regionsolution.interval_datetime AS settlementdate,
    'p5_regionsolution'::text AS source,
    p5_regionsolution.regionid,
    p5_regionsolution.totaldemand,
    p5_regionsolution.availablegeneration,
    p5_regionsolution.availableload,
    p5_regionsolution.demandforecast,
    p5_regionsolution.dispatchablegeneration,
    p5_regionsolution.dispatchableload,
    p5_regionsolution.netinterchange,
    p5_regionsolution.excessgeneration,
    p5_regionsolution.aggregatedispatcherror,
    p5_regionsolution.lastchanged,
    p5_regionsolution.initialsupply,
    p5_regionsolution.clearedsupply,
    p5_regionsolution.totalintermittentgeneration,
    p5_regionsolution.demand_and_nonschedgen,
    p5_regionsolution.uigf,
    p5_regionsolution.semischedule_clearedmw,
    p5_regionsolution.semischedule_compliancemw,
    p5_regionsolution.ss_solar_uigf,
    p5_regionsolution.ss_wind_uigf,
    p5_regionsolution.ss_solar_clearedmw,
    p5_regionsolution.ss_wind_clearedmw,
    p5_regionsolution.ss_solar_compliancemw,
    p5_regionsolution.ss_wind_compliancemw,
    p5_regionsolution.wdr_initialmw,
    p5_regionsolution.wdr_available,
    p5_regionsolution.wdr_dispatched,
    p5_regionsolution.ss_solar_availability,
    p5_regionsolution.ss_wind_availability,
    p5_regionsolution.bdu_energy_storage,
    p5_regionsolution.bdu_min_avail,
    p5_regionsolution.bdu_max_avail,
    p5_regionsolution.bdu_clearedmw_gen,
    p5_regionsolution.bdu_clearedmw_load,
    p5_regionsolution.bdu_initial_energy_storage
FROM p5_regionsolution
WHERE p5_regionsolution.interval_datetime > (
    (
        SELECT max(dispatch_regionsum.settlementdate) AS max
        FROM dispatch_regionsum
    )
);
