CREATE OR REPLACE VIEW public.dispatch_regionsum_p5_pdpasa AS
SELECT dispatch_regionsum.settlementdate,
    'dispatch_regionsum'::text AS source,
    dispatch_regionsum.regionid,
    dispatch_regionsum.totaldemand,
    dispatch_regionsum.availablegeneration,
    dispatch_regionsum.availableload,
    dispatch_regionsum.demandforecast,
    dispatch_regionsum.dispatchablegeneration,
    dispatch_regionsum.dispatchableload,
    dispatch_regionsum.netinterchange,
    dispatch_regionsum.excessgeneration,
    dispatch_regionsum.aggregatedispatcherror,
    dispatch_regionsum.lastchanged,
    dispatch_regionsum.initialsupply,
    dispatch_regionsum.clearedsupply,
    dispatch_regionsum.totalintermittentgeneration,
    dispatch_regionsum.demand_and_nonschedgen,
    dispatch_regionsum.uigf,
    dispatch_regionsum.semischedule_clearedmw,
    dispatch_regionsum.semischedule_compliancemw,
    dispatch_regionsum.ss_solar_uigf,
    dispatch_regionsum.ss_wind_uigf,
    dispatch_regionsum.ss_solar_clearedmw,
    dispatch_regionsum.ss_wind_clearedmw,
    dispatch_regionsum.ss_solar_compliancemw,
    dispatch_regionsum.ss_wind_compliancemw,
    dispatch_regionsum.wdr_initialmw,
    dispatch_regionsum.wdr_available,
    dispatch_regionsum.wdr_dispatched,
    dispatch_regionsum.ss_solar_availability,
    dispatch_regionsum.ss_wind_availability,
    dispatch_regionsum.bdu_energy_storage,
    dispatch_regionsum.bdu_min_avail,
    dispatch_regionsum.bdu_max_avail,
    dispatch_regionsum.bdu_clearedmw_gen,
    dispatch_regionsum.bdu_clearedmw_load,
    dispatch_regionsum.bdu_initial_energy_storage,
    NULL::numeric AS lor1level,
    NULL::numeric AS lor2level,
    NULL::numeric AS lor3level,
    NULL::numeric AS msr1level,
    NULL::numeric AS msr2level,
    NULL::numeric AS msr3level
FROM dispatch_regionsum
UNION ALL
SELECT p5_regionsolution.interval_datetime AS settlementdate,
    'p5_regionsolution'::text AS source,
    p5_regionsolution.regionid,
    p5_regionsolution.totaldemand,
    p5_regionsolution.availablegeneration,
    p5_regionsolution.availableload,
    p5_regionsolution.demandforecast,
    p5_regionsolution.dispatchablegeneration,
    p5_regionsolution.dispatchableload,
    p5_regionsolution.netinterchange,
    p5_regionsolution.excessgeneration,
    p5_regionsolution.aggregatedispatcherror,
    p5_regionsolution.lastchanged,
    p5_regionsolution.initialsupply,
    p5_regionsolution.clearedsupply,
    p5_regionsolution.totalintermittentgeneration,
    p5_regionsolution.demand_and_nonschedgen,
    p5_regionsolution.uigf,
    p5_regionsolution.semischedule_clearedmw,
    p5_regionsolution.semischedule_compliancemw,
    p5_regionsolution.ss_solar_uigf,
    p5_regionsolution.ss_wind_uigf,
    p5_regionsolution.ss_solar_clearedmw,
    p5_regionsolution.ss_wind_clearedmw,
    p5_regionsolution.ss_solar_compliancemw,
    p5_regionsolution.ss_wind_compliancemw,
    p5_regionsolution.wdr_initialmw,
    p5_regionsolution.wdr_available,
    p5_regionsolution.wdr_dispatched,
    p5_regionsolution.ss_solar_availability,
    p5_regionsolution.ss_wind_availability,
    p5_regionsolution.bdu_energy_storage,
    p5_regionsolution.bdu_min_avail,
    p5_regionsolution.bdu_max_avail,
    p5_regionsolution.bdu_clearedmw_gen,
    p5_regionsolution.bdu_clearedmw_load,
    p5_regionsolution.bdu_initial_energy_storage,
    NULL::numeric AS lor1level,
    NULL::numeric AS lor2level,
    NULL::numeric AS lor3level,
    NULL::numeric AS msr1level,
    NULL::numeric AS msr2level,
    NULL::numeric AS msr3level
FROM p5_regionsolution
WHERE p5_regionsolution.interval_datetime > (
    (
        SELECT max(dispatch_regionsum.settlementdate) AS max
        FROM dispatch_regionsum
    )
)
UNION ALL
SELECT pdpasa_regionsolution.interval_datetime AS settlementdate,
    'pdpasa_regionsolution'::text AS source,
    pdpasa_regionsolution.regionid,
    pdpasa_regionsolution.demand50 AS totaldemand,
    pdpasa_regionsolution.aggregatecapacityavailable AS availablegeneration,
    pdpasa_regionsolution.aggregatescheduledload AS availableload,
    pdpasa_regionsolution.energydemand50 AS demandforecast,
    NULL::numeric AS dispatchablegeneration,
    NULL::numeric AS dispatchableload,
    pdpasa_regionsolution.lorinterchangeunderscarcity AS netinterchange,
    NULL::numeric AS excessgeneration,
    NULL::numeric AS aggregatedispatcherror,
    pdpasa_regionsolution.lastchanged,
    NULL::numeric AS initialsupply,
    NULL::numeric AS clearedsupply,
    pdpasa_regionsolution.totalintermittentgeneration,
    pdpasa_regionsolution.demand_and_nonschedgen,
    pdpasa_regionsolution.uigf,
    pdpasa_regionsolution.semischeduledcapacity AS semischedule_clearedmw,
    NULL::numeric AS semischedule_compliancemw,
    pdpasa_regionsolution.ss_solar_uigf,
    pdpasa_regionsolution.ss_wind_uigf,
    pdpasa_regionsolution.ss_solar_cleared AS ss_solar_clearedmw,
    pdpasa_regionsolution.ss_wind_cleared AS ss_wind_clearedmw,
    NULL::numeric AS ss_solar_compliancemw,
    NULL::numeric AS ss_wind_compliancemw,
    NULL::numeric AS wdr_initialmw,
    pdpasa_regionsolution.wdr_available,
    NULL::numeric AS wdr_dispatched,
    pdpasa_regionsolution.ss_solar_capacity AS ss_solar_availability,
    pdpasa_regionsolution.ss_wind_capacity AS ss_wind_availability,
    NULL::numeric AS bdu_energy_storage,
    NULL::numeric AS bdu_min_avail,
    NULL::numeric AS bdu_max_avail,
    NULL::numeric AS bdu_clearedmw_gen,
    NULL::numeric AS bdu_clearedmw_load,
    NULL::numeric AS bdu_initial_energy_storage,
    pdpasa_regionsolution.calculatedlor1level AS lor1level,
    pdpasa_regionsolution.calculatedlor2level AS lor2level,
    0 AS lor3level,
    NULL::numeric AS msr1level,
    NULL::numeric AS msr2level,
    NULL::numeric AS msr3level
FROM pdpasa_regionsolution
WHERE pdpasa_regionsolution.interval_datetime > (
    (
        SELECT max(p5_regionsolution.interval_datetime) AS max
        FROM p5_regionsolution
    )
);
